[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "veritas-runtime"
version = "3.0.0"
description = "API that analyzes news content and verifies its veracity using AI."
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }

authors = [
    { name = "Eric Santos", email = "ericshantos13@gmail.com" }
]

dependencies = [
    "transformers>=5.5.0",
    "websockets>=15.0.1",
    "python-dotenv>=1.0.0"
]

[project.optional-dependencies]
cpu = [
    "torch>=2.0.0"
]

gpu = [
    "torch>=2.0.0"
]