[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "veritas-runtime"
description = "API that analyzes news content and verifies its veracity using AI.",
version = "2.2.0"
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }

authors = [
    { author = "Eric Santos", email = "ericshantos13@gmail.com" }
]

dependencies = [
    "tensorflow>=2.15.0",
    "Unidecode>=1.4.0",
    "spacy>=3.8.0",
    "huggingface_hub>=0.20.0",
    "websockets>=15.0.1"
]
